import { Constellation } from "./types";

export const constellationData: Constellation[] = [
  {
    id: "aries",
    name: "ARIES",
    symbol: "♈",
    element: "Fire",
    date: "March 21 - April 19",
    description: "Aries is one of the constellations zodiac. It is located in the Northern celestial hemisphere between Pisces to the west and Taurus to the east. It is one of the 48 constellations described by the 2nd century astronomer Ptolemy and remains one of the 88 modern constellations. It is a mid-sized constellation ranking 39th in overall size, with an area of 441 square degrees (1.1% of the celestial sphere).",
    historyImageUrl: "/src/assets/history/aries.svg",
    skyImageUrl: "/src/assets/skymap/aries.svg",
    symbolUrl: "/src/assets/symbols/aries.svg",
    imageUrl: "/src/assets/previews/aries.svg",
    rightAscension: "from 1h 40m to 3h 22m",
    declination: "from +9° 55' to +30° 40'",
    areaDegrees: 441.1,
    sizeRank: "eleventh",
    bordersCount: 5,
    borders: "Taurus, Perseus, Triangle, Pisces and Whale",
    brightestStars: "Hamal, Sheratan, Mesartim, Botein and Bharani",
    observationInfo: "Although Aries is considered an autumn constellation, it can be observed almost 10 months a year",
    observationPeriod: "— from June to March."
  },
  {
    id: "taurus",
    name: "TAURUS",
    symbol: "♉",
    element: "Earth",
    date: "April 20 - May 20",
    description: "Taurus is one of the constellations of the zodiac and is located in the Northern celestial hemisphere. Taurus is a large and prominent constellation in the northern hemisphere's winter sky. It is one of the oldest constellations, dating back to at least the Early Bronze Age when it marked the location of the Sun during the spring equinox.",
    historyImageUrl: "/src/assets/history/taurus.svg",
    skyImageUrl: "/src/assets/skymap/taurus.svg",
    symbolUrl: "/src/assets/symbols/taurus.svg",
    imageUrl: "/src/assets/previews/taurus.svg",
    rightAscension: "from 3h 20m to 6h 00m",
    declination: "from +0° 00' to +30° 00'",
    areaDegrees: 797.3,
    sizeRank: "seventh",
    bordersCount: 7,
    borders: "Aries, Perseus, Auriga, Gemini, Orion, Eridanus and Cetus",
    brightestStars: "Aldebaran, Elnath, Alcyone, Maia and Taygeta",
    observationInfo: "Taurus is visible during winter and early spring in the northern hemisphere",
    observationPeriod: "— from November to March."
  },
  {
    id: "gemini",
    name: "GEMINI",
    symbol: "♊",
    element: "Air",
    date: "May 21 - June 20",
    description: "Gemini is one of the constellations of the zodiac. It was one of the 48 constellations described by the 2nd century AD astronomer Ptolemy, and it remains one of the 88 modern constellations today. Its name is Latin for 'twins', and it is associated with the twins Castor and Pollux in Greek mythology.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Sidney_Hall_-_Urania%27s_Mirror_-_Gemini.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Gemini.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Gemini_IAU.svg/800px-Gemini_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Gemini.svg/240px-Gemini.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Sidney_Hall_-_Urania%27s_Mirror_-_Gemini.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Gemini.jpg",
    rightAscension: "from 5h 59m to 8h 12m",
    declination: "from +10° 00' to +35° 00'",
    areaDegrees: 513.8,
    sizeRank: "twenty-sixth",
    bordersCount: 6,
    borders: "Taurus, Auriga, Lynx, Cancer, Canis Minor and Orion",
    brightestStars: "Pollux, Castor, Alhena, Propus and Tejat",
    observationInfo: "Gemini is visible in winter through spring in the northern hemisphere",
    observationPeriod: "— from December to May."
  },
  {
    id: "cancer",
    name: "CANCER",
    symbol: "♋",
    element: "Water",
    date: "June 21 - July 22",
    description: "Cancer is one of the twelve constellations of the zodiac and is located in the Northern celestial hemisphere. Its name is Latin for crab and it is commonly represented as one. Cancer is a medium-sized constellation with an area of 506 square degrees and its brightest star is β Cancri, with an apparent magnitude of 3.5.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sidney_Hall_-_Urania%27s_Mirror_-_Cancer.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Cancer.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Cancer_IAU.svg/800px-Cancer_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Cancer.svg/240px-Cancer.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sidney_Hall_-_Urania%27s_Mirror_-_Cancer.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Cancer.jpg",
    rightAscension: "from 7h 51m to 9h 24m",
    declination: "from +6° 30' to +33° 00'",
    areaDegrees: 506.0,
    sizeRank: "thirty-first",
    bordersCount: 5,
    borders: "Gemini, Lynx, Leo Minor, Leo and Hydra",
    brightestStars: "Tarf, Asellus Australis, Acubens, Asellus Borealis and Tegmine",
    observationInfo: "Cancer is most visible in the northern hemisphere during early spring",
    observationPeriod: "— from January to May."
  },
  {
    id: "leo",
    name: "LEO",
    symbol: "♌",
    element: "Fire",
    date: "July 23 - August 22",
    description: "Leo is one of the constellations of the zodiac, lying between Cancer to the west and Virgo to the east. Leo is a prominent constellation in the northern hemisphere's spring sky, appearing during the spring in the Northern Hemisphere and the autumn in the Southern Hemisphere. It is one of the 48 constellations described by the 2nd-century astronomer Ptolemy.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Sidney_Hall_-_Urania%27s_Mirror_-_Leo_Major_and_Leo_Minor.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Leo_Major_and_Leo_Minor.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Leo_IAU.svg/800px-Leo_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Leo.svg/240px-Leo.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Sidney_Hall_-_Urania%27s_Mirror_-_Leo_Major_and_Leo_Minor.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Leo_Major_and_Leo_Minor.jpg",
    rightAscension: "from 9h 21m to 11h 57m",
    declination: "from -0° 30' to +33° 00'",
    areaDegrees: 946.9,
    sizeRank: "twelfth",
    bordersCount: 7,
    borders: "Cancer, Leo Minor, Ursa Major, Coma Berenices, Virgo, Crater and Hydra",
    brightestStars: "Regulus, Denebola, Algieba, Zosma and Chertan",
    observationInfo: "Leo is visible in the Northern Hemisphere during spring",
    observationPeriod: "— from March to June."
  },
  {
    id: "virgo",
    name: "VIRGO",
    symbol: "♍",
    element: "Earth",
    date: "August 23 - September 22",
    description: "Virgo is one of the constellations of the zodiac. Its name is Latin for virgin, and its symbol is ♍. Lying between Leo to the west and Libra to the east, it is the second-largest constellation in the sky (after Hydra) and the largest constellation in the zodiac. It can be easily found through its brightest star, Spica.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Sidney_Hall_-_Urania%27s_Mirror_-_Virgo.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Virgo.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Virgo_IAU.svg/800px-Virgo_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Virgo.svg/240px-Virgo.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Sidney_Hall_-_Urania%27s_Mirror_-_Virgo.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Virgo.jpg",
    rightAscension: "from 11h 45m to 15h 45m",
    declination: "from -22° 00' to +15° 00'",
    areaDegrees: 1294.4,
    sizeRank: "second",
    bordersCount: 9,
    borders: "Leo, Coma Berenices, Boötes, Serpens, Libra, Hydra, Crater, Corvus and Centaurus",
    brightestStars: "Spica, Porrima, Vindemiatrix, Auva and Heze",
    observationInfo: "Virgo is visible in the evening sky from March to July, reaching highest in May",
    observationPeriod: "— from March to July."
  },
  {
    id: "libra",
    name: "LIBRA",
    symbol: "♎",
    element: "Air",
    date: "September 23 - October 22",
    description: "Libra is one of the 12 zodiac constellations, located in the southern celestial hemisphere. Its name is Latin for 'weighing scales', making it the only zodiac constellation that represents an inanimate object. Libra was known in Babylonian astronomy as MUL Zibanu (the 'scales' or 'balance'), and was directly associated with the scales or the claws of Scorpius the scorpion.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Sidney_Hall_-_Urania%27s_Mirror_-_Libra.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Libra.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Libra_IAU.svg/800px-Libra_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Libra.svg/240px-Libra.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Sidney_Hall_-_Urania%27s_Mirror_-_Libra.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Libra.jpg",
    rightAscension: "from 14h 17m to 16h 09m",
    declination: "from -30° 00' to -0° 30'",
    areaDegrees: 538.1,
    sizeRank: "twenty-ninth",
    bordersCount: 5,
    borders: "Virgo, Serpens, Ophiuchus, Scorpius and Hydra",
    brightestStars: "Zubeneschamali, Zubenelgenubi, Brachium, Zubenelhakrabi and Upsilon Librae",
    observationInfo: "Libra is visible between April and July in the evening sky",
    observationPeriod: "— from April to August."
  },
  {
    id: "scorpio",
    name: "SCORPIO",
    symbol: "♏",
    element: "Water",
    date: "October 23 - November 21",
    description: "Scorpius is one of the constellations of the zodiac and is located in the Southern celestial hemisphere. Scorpius is one of the 48 constellations identified by the Greek astronomer Ptolemy in the 2nd century. Its bright stars form a distinctive pattern like a scorpion, with the red supergiant Antares representing the heart of the creature.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Sidney_Hall_-_Urania%27s_Mirror_-_Scorpio.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Scorpio.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Scorpius_IAU.svg/800px-Scorpius_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Scorpio.svg/240px-Scorpio.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Sidney_Hall_-_Urania%27s_Mirror_-_Scorpio.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Scorpio.jpg",
    rightAscension: "from 15h 42m to 17h 59m",
    declination: "from -46° 00' to -8° 00'",
    areaDegrees: 496.8,
    sizeRank: "thirty-third",
    bordersCount: 7,
    borders: "Libra, Ophiuchus, Sagittarius, Corona Australis, Ara, Norma and Lupus",
    brightestStars: "Antares, Shaula, Sargas, Dschubba and Larawag",
    observationInfo: "Scorpius is best viewed during Southern Hemisphere winter and Northern Hemisphere summer",
    observationPeriod: "— from May to August."
  },
  {
    id: "sagittarius",
    name: "SAGITTARIUS",
    symbol: "♐",
    element: "Fire",
    date: "November 22 - December 21",
    description: "Sagittarius is one of the constellations of the zodiac and is located in the Southern celestial hemisphere. Its name is Latin for 'archer', and its symbol is a stylized arrow. Sagittarius is commonly represented as a centaur pulling a bow. It lies between Scorpius and Capricornus on the ecliptic. It contains the galactic center of the Milky Way.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Sidney_Hall_-_Urania%27s_Mirror_-_Sagittarius_and_Corona_Australis.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Sagittarius_and_Corona_Australis.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Sagittarius_IAU.svg/800px-Sagittarius_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Sagittarius.svg/240px-Sagittarius.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Sidney_Hall_-_Urania%27s_Mirror_-_Sagittarius_and_Corona_Australis.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Sagittarius_and_Corona_Australis.jpg",
    rightAscension: "from 17h 41m to 20h 14m",
    declination: "from -45° 00' to -12° 00'",
    areaDegrees: 867.4,
    sizeRank: "fifteenth",
    bordersCount: 8,
    borders: "Scutum, Serpens Cauda, Ophiuchus, Scorpius, Corona Australis, Telescopium, Microscopium and Capricornus",
    brightestStars: "Kaus Australis, Nunki, Ascella, Kaus Media and Kaus Borealis",
    observationInfo: "Sagittarius is visible in the southern hemisphere during winter and in the northern hemisphere during summer",
    observationPeriod: "— from June to September."
  },
  {
    id: "capricorn",
    name: "CAPRICORN",
    symbol: "♑",
    element: "Earth",
    date: "December 22 - January 19",
    description: "Capricornus is one of the constellations of the zodiac. Its name is Latin for 'horned goat' or 'goat horn' or 'having horns like a goat's', and it is commonly represented in the form of a sea-goat: a mythical creature that is half goat, half fish. Its symbol is ♑. Capricornus is one of the 88 modern constellations, and was also one of the 48 constellations listed by the 2nd century astronomer Ptolemy.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Sidney_Hall_-_Urania%27s_Mirror_-_Capricornus.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Capricornus.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Capricornus_IAU.svg/800px-Capricornus_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Capricorn.svg/240px-Capricorn.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Sidney_Hall_-_Urania%27s_Mirror_-_Capricornus.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Capricornus.jpg",
    rightAscension: "from 20h 03m to 22h 00m",
    declination: "from -27° 00' to -9° 00'",
    areaDegrees: 413.9,
    sizeRank: "fortieth",
    bordersCount: 6,
    borders: "Aquila, Sagittarius, Microscopium, Piscis Austrinus, Aquarius and Delphinus",
    brightestStars: "Deneb Algedi, Dabih, Nashira, Deneb Algiedi and Alshat",
    observationInfo: "Capricornus is visible in the southern hemisphere during winter and in the northern hemisphere during summer",
    observationPeriod: "— from July to November."
  },
  {
    id: "aquarius",
    name: "AQUARIUS",
    symbol: "♒",
    element: "Air",
    date: "January 20 - February 18",
    description: "Aquarius is a constellation of the zodiac, situated between Capricornus and Pisces. Its name is Latin for 'water-carrier' or 'cup-carrier', and its symbol is ♒, a representation of water. Aquarius is one of the oldest of the recognized constellations along the zodiac (the apparent path of the Sun across the celestial sphere over the course of the year).",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Sidney_Hall_-_Urania%27s_Mirror_-_Aquarius.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Aquarius.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Aquarius_IAU.svg/800px-Aquarius_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Aquarius.svg/240px-Aquarius.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Sidney_Hall_-_Urania%27s_Mirror_-_Aquarius.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Aquarius.jpg",
    rightAscension: "from 20h 38m to 23h 57m",
    declination: "from -25° 00' to +3° 00'",
    areaDegrees: 979.9,
    sizeRank: "tenth",
    bordersCount: 8,
    borders: "Pegasus, Equuleus, Delphinus, Aquila, Capricornus, Piscis Austrinus, Sculptor and Cetus",
    brightestStars: "Sadalsuud, Sadalmelik, Sadalbachia, Skat and Sadachbia",
    observationInfo: "Aquarius is visible in the southern hemisphere during spring and in the northern hemisphere during autumn",
    observationPeriod: "— from August to November."
  },
  {
    id: "pisces",
    name: "PISCES",
    symbol: "♓",
    element: "Water",
    date: "February 19 - March 20",
    description: "Pisces is one of the constellations of the zodiac. Its name is the Latin plural for fish. It lies between Aquarius to the west and Aries to the east. The ecliptic and the celestial equator intersect within this constellation and in Virgo. Its symbol is ♓︎. Pisces is the twelfth and last astrological sign in the Zodiac and originates from the Pisces constellation.",
    historyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Sidney_Hall_-_Urania%27s_Mirror_-_Pisces.jpg/800px-Sidney_Hall_-_Urania%27s_Mirror_-_Pisces.jpg",
    skyImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Pisces_IAU.svg/800px-Pisces_IAU.svg.png",
    symbolUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Pisces.svg/240px-Pisces.svg.png",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Sidney_Hall_-_Urania%27s_Mirror_-_Pisces.jpg/440px-Sidney_Hall_-_Urania%27s_Mirror_-_Pisces.jpg",
    rightAscension: "from 22h 52m to 2h 04m",
    declination: "from -7° 00' to +33° 00'",
    areaDegrees: 889.4,
    sizeRank: "fourteenth",
    bordersCount: 7,
    borders: "Pegasus, Andromeda, Triangulum, Aries, Cetus, Aquarius and Delphinus",
    brightestStars: "Eta Piscium, Gamma Piscium, Omega Piscium, Iota Piscium and Omicron Piscium",
    observationInfo: "Pisces is visible in the northern hemisphere during autumn and winter",
    observationPeriod: "— from September to February."
  }
];
